### ISSUE TITLE
ParamSpider - urllib3 issue

### ISSUE THREAD

**Issue by N0rdicSec** [0xKayala/NucleiFuzzer#12]
I've installed it as advised, but there is a lib dependency, as shown below.

I tried to install the lib requested manually, with no lucky.

[urllib3 1.26.5](https://github.com/urllib3/urllib3/releases/tag/1.26.5)

## Error:

```
Installing Nuclei...                                                                                                                              
Running ParamSpider on vulnweb.com
/usr/local/lib/python3.11/dist-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (**1.26.5**) or chardet (5.2.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
```

![image](https://github.com/0xKayala/NucleiFuzzer/assets/46175778/727a8b8a-9881-43da-b831-66fa9dd5c273)

Thank you.

**Comment by N0rdicSec** [comment]
The line 83 refers to the command `nuclei` as shown above. So I decided to install nuclei manually and it solved the problem. 

```
git clone https://github.com/projectdiscovery/nuclei.git; \
cd nuclei/v2/cmd/nuclei; \
go build; \
mv nuclei /usr/local/bin/; \
nuclei -version;
```

[Nuclei GitHub Documentation](https://docs.nuclei.sh/getting-started/install)

## Execution

![image](https://github.com/0xKayala/NucleiFuzzer/assets/46175778/c8f9410a-18ce-4459-8c62-bca22f9a7628)

**Comment by 0xKayala** [comment]
Good to see that you have resolved the issue
