### ISSUE TITLE
Problem with the tool 

### ISSUE THREAD

**Issue by Hany5k** [0xKayala/NucleiFuzzer#16]
Hello brother, there is a problem with the tool. Is there a solution?

**Comment by Hany5k** [comment]
![Uploading Screenshot_20231128_210503_com.huawei.himovie.overseas.jpg…]()

**Comment by 0xKayala** [comment]
Can you please specify the problem or the issue which you are facing so that i can help you with it

**Comment by Hany5k** [comment]
Brother, this is the problem. Please help me solve it 
![Screenshot_20231130_203452](https://github.com/0xKayala/NucleiFuzzer/assets/118838534/7ebcbeaa-9594-4e01-9fd5-deed4f06de32)

**Comment by 0xKayala** [comment]
It seems like you haven't installed the nuclei tool on your machine.

Make sure to follow the below repo to install the nuclei tool and check whether the tool is working or not, if it is not working then move the nuclei tool to "/usr/bin" path and then check it

Link: https://github.com/projectdiscovery/nuclei

**Comment by Hany5k** [comment]
Thank you very much, I will try the solution
