### ISSUE TITLE
FTL error

### ISSUE THREAD

**Issue by kraken01100** [0xKayala/NucleiFuzzer#19]
Hi i have a problem 

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Supplied input was automatically deduplicated (11 removed).
[WRN] Found 22 templates with syntax error (use -validate flag for further examination)
[INF] Using Nuclei Engine 2.7.7 (latest)
[INF] Using Nuclei Templates 9.2.2 (latest)
[FTL] Could not run nuclei: no valid templates were found
Scan is completed - Happy Fuzzing

**Comment by 0xKayala** [comment]
Make sure the "fuzzing-templates" are present on your home directory and nuclei tool is up to date so that you can use the nucleifuzzer without any issue
