### ISSUE TITLE
Error: No such option: -s

### ISSUE THREAD

**Issue by somersbyy** [0xKayala/NucleiFuzzer#23]
![Screenshot_1](https://github.com/0xKayala/NucleiFuzzer/assets/52800090/8a99d09e-75f8-49e0-93c0-1bfb43a1af72)

Hello! How to fix this?
Error: No such option: -s

**Comment by 0xKayala** [comment]
You are using python based httpx tool that is why you are facing this issue. Uninstall it and install the projectdiscovery's httpx go based tool so that you can use the nucleifuzzer tool

pip uninstall httpx

go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest

**Comment by somersbyy** [comment]
Thanks for the help!
