### ISSUE TITLE
No templates error

### ISSUE THREAD

**Issue by mina0x00** [0xKayala/NucleiFuzzer#26]
[INF] Supplied input was automatically deduplicated (12 removed).
[INF] Current nuclei version: v3.2.2 (latest)
[INF] Current nuclei-templates version: v9.7.8 (latest)
[WRN] Scan results upload to cloud is disabled.
[WRN] Loaded 21 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 224
[INF] No results found. Better luck next time!
[FTL] Could not run nuclei: no templates provided for scan
Scan is completed - Happy Fuzzing

nf -d vulnweb.com

I have the fuzzing-templates installed aswell in my root directory.

**Comment by 0xKayala** [comment]
Thank you for bring this issue to our Attention.

It looks like the latest Nuclei version is not working properly with the fuzzing templates as shown in the below image:

![image](https://github.com/0xKayala/NucleiFuzzer/assets/16838353/c6b21f74-33f4-4572-865c-9c277e537a6d)

We will work on it and update the script asap

**Comment by mina0x00** [comment]
> Thank you for bring this issue to our Attention.
> 
> It looks like the latest Nuclei version is not working properly with the fuzzing templates as shown in the below image:
> 
> ![image](https://private-user-images.githubusercontent.com/16838353/313953604-c6b21f74-33f4-4572-865c-9c277e537a6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MzU5NDQsIm5iZiI6MTcxMDgzNTY0NCwicGF0aCI6Ii8xNjgzODM1My8zMTM5NTM2MDQtYzZiMjFmNzQtMzNmNC00NTcyLTg2NWMtOWMyNzdlNTM3YTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA4MDcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhYjFjMmY5NzRjN2I2YjVkYTc2NTFkMTE1NGE0MTg2Y2NkYzRjYzk4N2NhZjg3NmU2ZmQ3NzVkMzg3OTg2NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.23MaZ4yn7JgNUFfbPU0Nj1VYvt_EAekqfD2OjatuoZY)
> 
> We will work on it and update the script asap

No problem! :)

**Comment by 0xKayala** [comment]
Can you try it now and let us know whether it is working or not

**Comment by mina0x00** [comment]
It's working now. But I'm receiving this error now https://i.imgur.com/MHUXuoO.png Unless this is normal?

**Comment by 0xKayala** [comment]
Yes, This is normal as the newly updated Nuclei tool is throwing some syntax errors within its output. We will work on it to surpass those errors in the upcoming upgrade.
