### ISSUE TITLE
after giving domain name 

### ISSUE THREAD

**Issue by r0x5r** [0xKayala/NucleiFuzzer#27]
└─# nf -d testphp.vulnweb.com

                     __     _ ____
   ____  __  _______/ /__  (_) __/_  __________  ___  _____
  / __ \/ / / / ___/ / _ \/ / /_/ / / /_  /_  / / _ \/ ___/
 / / / / /_/ / /__/ /  __/ / __/ /_/ / / /_/ /_/  __/ /
/_/ /_/\__,_/\___/_/\___/_/_/  \__,_/ /___/___/\___/_/   v1.0.2

                               Made by Satya Prakash (0xKayala)

Running ParamSpider on testphp.vulnweb.com

         ___                               _    __
        / _ \___ ________ ___ _  ___ ___  (_)__/ /__ ____
       / ___/ _ `/ __/ _ `/  ' \(_-</ _ \/ / _  / -_) __/
      /_/   \_,_/_/  \_,_/_/_/_/___/ .__/_/\_,_/\__/_/
                                  /_/

                            - coded with <3 by Devansh Batham

[!] URLS containing these extensions will be excluded from the results   : ['.png', '.jpg', '.gif', '.jpeg', '.swf', '.woff', '.svg', '.pdf', '.json', '.css', '.js', '.webp', '.woff', '.woff2', '.eot', '.ttf', '.otf', '.mp4', '.txt']

[+] Total number of retries:  0
[+] Total unique urls found : 216
[+] Output is saved here : output/testphp.vulnweb.com.yaml

[!] Total execution time      : 1.5574s
Running Nuclei on collected URLs
flag provided but not defined: -fuzz
Scan is completed - Happy Fuzzing

nucllie fuzzer not running automatic we need to give this command nuclei -t fuzzing-templates -list fuzz_endpoints.txt all the time

**Comment by r0x5r** [comment]
also add katan if some one want to use katana for  urls then they can use that

**Comment by 0xKayala** [comment]
Please update your nuclei tool to the latest version and don't give the subdomain as a target.

Try with the main domain as shown in the below pic: Try it a couple of times to check.

![image](https://github.com/0xKayala/NucleiFuzzer/assets/16838353/de6077c9-f6d9-4335-88db-4b11b3b50a7a)
![image](https://github.com/0xKayala/NucleiFuzzer/assets/16838353/5b158320-8dd9-42c2-a99f-2e4e332599c1)

**Comment by r0x5r** [comment]
![image](https://github.com/0xKayala/NucleiFuzzer/assets/84601356/01fcaece-c0a0-4286-8040-91049e45acf0)
check here

**Comment by 0xKayala** [comment]
Try to run the command a couple of times and outside of the root

**Comment by zevopk** [comment]
Hi,  @0xKayala 

Thank you for the great tool.

I have the same problem 

![Screenshot_2024-04-17_12-32-21](https://github.com/0xKayala/NucleiFuzzer/assets/46140039/b6a10747-d8d2-4c59-bff1-1721b3bb47a2)



And All the required Tools works well in my terminal

![Screenshot_2024-04-17_12-33-55](https://github.com/0xKayala/NucleiFuzzer/assets/46140039/1c9b00d1-6e86-4998-ab65-de1fa78ebabd)




Also I have all required directories in $HOME

![Screenshot_2024-04-17_12-34-34](https://github.com/0xKayala/NucleiFuzzer/assets/46140039/c5a3c4d4-518b-4ca0-9248-25065caf9d4a)

**Comment by 0xKayala** [comment]
I have used the below command in the NucleiFuzzer Script to run Nuclei tool on the collected URLs from Paramspider.

``sort "output/$domain.yaml" | uniq | tee "output/$domain.yaml" | httpx -silent -mc 200,301,302,403 | nuclei -t "$home_dir/fuzzing-templates" -fuzz -rl 05``

So, Sometimes the collected URLs were captured or passed to nuclei due to some issue with the Nuclei Tool. This is a known issue as it is happening even if I modify the script as shown below.

``nuclei -l "output/$domain.yaml" -t "$home_dir/fuzzing-templates" -fuzz -rl 05``

Just waiting for the update of Nuclei tool from @projectdiscovery team in order to fix this issue in capturing or passing the URLs to Nuclei tool.

However, if you run the current existing script for 3 to 4 times, it will work.

**Comment by 0xKayala** [comment]
**Output:** Try to execute the script 3 to 4 times.

![image](https://github.com/0xKayala/NucleiFuzzer/assets/16838353/2d6fbf75-be63-4b40-ab29-7096c3fe187b)

![image](https://github.com/0xKayala/NucleiFuzzer/assets/16838353/fdd7711c-36dd-4298-90d9-1588cbfef32d)

**Comment by r0x5r** [comment]
bhai ek hi screenshot lo na yeh dusra screen shot asa alg lerha ho kuch tho gadbad hai

**Comment by 0xKayala** [comment]
@r0x5r Bro, Ek screenshot me pura nahi dhikra.

Isliye jithna dhikra hai, uthna capture kiya hai

For your satisfaction here is the single screenshot below

![image](https://github.com/0xKayala/NucleiFuzzer/assets/16838353/2ae30b41-b818-45ad-9bbc-6706ad9ad06e)

**Comment by zevopk** [comment]
Hi, @0xKayala 
I have fixed the issue just by changing the file extension in the `tee` command in `NucleiFuzzer.sh` file
from `tee "output/$domain.yaml"`
to `tee "output/$domain.txt"`

The tool works very well now.


![Screenshot_2024-04-18_10-34-46](https://github.com/0xKayala/NucleiFuzzer/assets/46140039/cc049fc1-48f3-46a4-ad10-23594a40b496)

Hope This Helps!

**Comment by 0xKayala** [comment]
Previously I have used TXT file only but still I faced the same issue. That is why I changed it to yaml as it saves too fast for yaml format.

**Comment by zevopk** [comment]
I didn't face any problems since I have edited it. However, The tool is a little bit slow to initialize the scan.

**Comment by 0xKayala** [comment]
> sort "output/$domain.yaml" - I think you forgot to change the extension here

**Comment by 0xKayala** [comment]
> Hi, @0xKayala I have fixed the issue just by changing the file extension in the `tee` command in `NucleiFuzzer.sh` file from `tee "output/$domain.yaml"` to `tee "output/$domain.txt"`
> 
> The tool works very well now.
> 
> ![Screenshot_2024-04-18_10-34-46](https://private-user-images.githubusercontent.com/46140039/323545122-cc049fc1-48f3-46a4-ad10-23594a40b496.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MTAxMzQsIm5iZiI6MTcxMzYwOTgzNCwicGF0aCI6Ii80NjE0MDAzOS8zMjM1NDUxMjItY2MwNDlmYzEtNDhmMy00NmE0LWFkMTAtMjM1OTRhNDBiNDk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDEwNDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NmEzN2E2MGZhMjZkZGE5NzZjOTA2MzQ1YzQzMmNjZTFiNGRkNDgwYzUxNjhhODQyNDJiY2JhMzdhMTAxNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b1hcXdvfwwabKL8lKgvpm6sggtkLLnEdLhzHsJTLxOo)
> 
> Hope This Helps!


The issue with the script lies in how the output files are handled and passed to the nuclei command. Specifically, the output file generated by `ParamSpider` (output/$domain.yaml) is being overwritten by the tee command before it can be passed to `httpx` and then to `nuclei`. This is why `nuclei` is not receiving the URLs for scanning.

To fix this, I have modified the script to use a temporary file to store the sorted and unique URLs before passing them to `httpx` and `nuclei`. Here's the updated portion of the script:

```
# Step 5: Run the Nuclei Fuzzing templates on the collected URLs
echo "Running Nuclei on collected URLs"
if [ -n "$domain" ]; then
    # Use a temporary file to store the sorted and unique URLs
    temp_file=$(mktemp)
    sort "output/$domain.yaml" | uniq > "$temp_file"
    httpx -silent -mc 200,301,302,403 -l "$temp_file" | nuclei -t "$home_dir/fuzzing-templates" -fuzz -rl 05
    rm "$temp_file"  # Remove the temporary file
elif [ -n "$filename" ]; then
    sort "$output_file" | uniq > "$temp_file"
    httpx -silent -mc 200,301,302,403 -l "$temp_file" | nuclei -t "$home_dir/fuzzing-templates" -fuzz -rl 05
    rm "$temp_file"  # Remove the temporary file
fi
```

This modification creates a temporary file ($temp_file) to store the sorted and unique URLs, which are then passed to `httpx` for scanning. After the scanning is complete, the temporary file is removed. This should ensure that the collected URLs are properly passed to `nuclei` for scanning.
