### ISSUE TITLE
No such

### ISSUE THREAD

**Issue by iP010** [0xKayala/NucleiFuzzer#29]
Running Nuclei on collected URLs

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.3.0

                projectdiscovery.io

Usage: httpx [OPTIONS] URL

Error: No such option: -s
[WRN] Found 156 templates loaded with deprecated protocol syntax, update before v3 for continued support.
[INF] Current nuclei version: v3.3.0 (latest)
[INF] Current nuclei-templates version: v9.9.2 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 67
[INF] Templates loaded for current scan: 25
[INF] Executing 25 signed templates from projectdiscovery/nuclei-templates
[INF] No results found. Better luck next time!
Scanning is completed - Happy Fuzzing

**Comment by alexpeleg** [comment]
Same issue here:
Usage: httpx [OPTIONS] URL

Error: No such option: -s
[INF] Current nuclei version: v3.2.9 (outdated)
[INF] Current nuclei-templates version: v9.9.2 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 67
[INF] Templates loaded for current scan: 24
[INF] Executing 24 signed templates from projectdiscovery/nuclei-templates
[INF] No results found. Better luck next time!
Scanning is completed - Happy Fuzzing

**Comment by 0xKayala** [comment]
Please find the solution for it on below link:

**[Solution](https://github.com/0xKayala/NucleiFuzzer/issues/22#issuecomment-1860448391)**
