### ISSUE TITLE
flag provided but not defined: -dast

### ISSUE THREAD

**Issue by r3xbugbounty** [0xKayala/NucleiFuzzer#33]
After installed the nucleifuzzer, but it show the following error. I don't know to fix it
![image](https://github.com/user-attachments/assets/e2b28b87-5e1e-48c1-a1f8-54fae138ea45)

**Comment by tXambe** [comment]
Hello,

same error 

```
[!] Total execution time      : 2.586s                                                                                                                                                        
Running Nuclei on collected URLs
Usage: httpx [OPTIONS] URL

Error: No such option: -s

```

**Comment by 0xKayala** [comment]
Uninstall python based httpx and install go based httpx from project discovery

**Comment by 0xKayala** [comment]
Find the solution here: **[Solution](https://github.com/0xKayala/NucleiFuzzer/issues/22#issuecomment-1860448391)**
