### ISSUE TITLE
flag provided but not defined: -dast

### ISSUE THREAD

**Issue by ChathurangaBW** [0xKayala/NucleiFuzzer#36]
[!] Total execution time      : 2.497s                                                                                                                                                                                                      
Running Nuclei on collected URLs
flag provided but not defined: -dast
Scanning is completed - Happy Fuzzing
I have installed the httpx and all other modules from the GitHub repository. 
![image](https://github.com/user-attachments/assets/ab6d9e08-8b97-4c4b-a224-3143711e3dbd)

**Comment by 0xKayala** [comment]
It looks like you are using outdated nuclei version, please update the nuclei tool and httpx tool and then try to run this tool
