### ISSUE TITLE
errors 

### ISSUE THREAD

**Issue by mdsabbirkhan** [0xKayala/NucleiFuzzer#37]
nf -d www.vodafone.om

    _   __           __     _ ____
   / | / /_  _______/ /__  (_) __/_  __________  ___  _____
  /  |/ / / / / ___/ / _ \/ / /_/ / / /_  /_  / / _ \/ ___/
 / /|  / /_/ / /__/ /  __/ / __/ /_/ / / /_/ /_/  __/ /
/_/ |_/\__,_/\___/_/\___/_/_/  \__,_/ /___/___/\___/_/   v1.0.3

                               Made by Satya Prakash (0xKayala)

Running ParamSpider on www.taeget.com

         ___                               _    __
        / _ \___ ________ ___ _  ___ ___  (_)__/ /__ ____
       / ___/ _ `/ __/ _ `/  ' \(_-</ _ \/ / _  / -_) __/
      /_/   \_,_/_/  \_,_/_/_/_/___/ .__/_/\_,_/\__/_/
                                  /_/

                            - coded with <3 by Devansh Batham

[!] URLS containing these extensions will be excluded from the results   : ['.png', '.jpg', '.gif', '.jpeg', '.swf', '.woff', '.svg', '.pdf', '.json', '.css', '.js', '.webp', '.woff', '.woff2', '.eot', '.ttf', '.otf', '.mp4', '.txt']

Traceback (most recent call last):
  File "/home/cyber/ParamSpider/paramspider.py", line 95, in <module>
    main()
  File "/home/cyber/ParamSpider/paramspider.py", line 72, in main
    save_it.save_func(final_uris , args.output , args.domain)
  File "/home/cyber/ParamSpider/core/save_it.py", line 19, in save_func
    with open(filename, "a", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotADirectoryError: [Errno 20] Not a directory: 'output/taeget.com.yaml'
No URLs found for the domain www.taeget.com. Exiting...

**Comment by 0xKayala** [comment]
Bro, try to give the syntax correctly as shown in the below format without www or http/https:

nf -d vulnweb.com

**Comment by mdsabbirkhan** [comment]
nf -d vulnweb.com

    _   __           __     _ ____
   / | / /_  _______/ /__  (_) __/_  __________  ___  _____
  /  |/ / / / / ___/ / _ \/ / /_/ / / /_  /_  / / _ \/ ___/
 / /|  / /_/ / /__/ /  __/ / __/ /_/ / / /_/ /_/  __/ /
/_/ |_/\__,_/\___/_/\___/_/_/  \__,_/ /___/___/\___/_/   v1.0.3

                               Made by Satya Prakash (0xKayala)

Running ParamSpider on vulnweb.com


         ___                               _    __
        / _ \___ ________ ___ _  ___ ___  (_)__/ /__ ____
       / ___/ _ `/ __/ _ `/  ' \(_-</ _ \/ / _  / -_) __/
      /_/   \_,_/_/  \_,_/_/_/_/___/ .__/_/\_,_/\__/_/
                                  /_/

                            - coded with <3 by Devansh Batham

[!] URLS containing these extensions will be excluded from the results   : ['.png', '.jpg', '.gif', '.jpeg', '.swf', '.woff', '.svg', '.pdf', '.json', '.css', '.js', '.webp', '.woff', '.woff2', '.eot', '.ttf', '.otf', '.mp4', '.txt']

Traceback (most recent call last):
  File "/home/cyber/ParamSpider/paramspider.py", line 95, in <module>
    main()
  File "/home/cyber/ParamSpider/paramspider.py", line 72, in main
    save_it.save_func(final_uris , args.output , args.domain)
  File "/home/cyber/ParamSpider/core/save_it.py", line 19, in save_func
    with open(filename, "a", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotADirectoryError: [Errno 20] Not a directory: 'output/vulnweb.com.yaml'
No URLs found for the domain vulnweb.com. Exiting...

**Comment by 0xKayala** [comment]
There could be some issues with the tools on your machine. Please uninstall and reinstall them and try to execute the tool as a fresh as I am not facing any issues from my end as shown in the below screenshot which I just executed now.

![image](https://github.com/user-attachments/assets/3304b12d-60d6-4b2b-ac0d-f629509d2da3)
![image](https://github.com/user-attachments/assets/757a0945-077c-48da-9a40-f86dfcfedfad)
![image](https://github.com/user-attachments/assets/9a4da274-7594-40a7-a84c-660895b19a50)
