### ISSUE TITLE
Suddenly unavailable

### ISSUE THREAD

**Issue by yiufungmak** [0xKayala/NucleiFuzzer#40]
503 
<img width="1495" alt="截屏2024-10-25 14 27 50" src="https://github.com/user-attachments/assets/c27dea2e-ee65-4edf-8521-f2cb3417c69b">

**Comment by 0xKayala** [comment]
It looks like the web archive is not working properly, so the URLs were not collected by the Paramspider tool. Wait for some days and try again.

**Comment by yiufungmak** [comment]
All urls are unavailable
