### ISSUE TITLE
No URLs Found. Exiting...

### ISSUE THREAD

**Issue by sasholy** [0xKayala/NucleiFuzzer#7]
hello
 I can't run nuclei.

[+] Total number of retries:  0
[+] Total unique urls found : 82
[+] Output is saved here : http://testphp.vulnweb.com/-paramspider_output.txt            
                                                                                         
[!] Total execution time      : 8.565s                                                   
No URLs Found. Exiting...
thx.

**Comment by clem9669** [comment]
Hi, I have an issue that might be similar to this one. It is about supporting subdomains.

The tool fail every time the -d is a subdomain

Cheers

**Comment by 0xKayala** [comment]
I have made some necessary changes to the tool and it doesn't support the subdomain as a target but still, you can get all the URLs along with the subdomain URLs if it is found in the web archives by paramspider tool.

Now the Paramspider tool has been updated, so made necessary corrections to it
