### ISSUE TITLE
Please, -f for file.txt

### ISSUE THREAD

**Issue by Tripse** [0xKayala/NucleiFuzzer#9]
thankyou sir

**Comment by 0xKayala** [comment]
The newly updated ParamSpider supports -f or file.txt, but it is not giving an accurate result of output where nuclei can detect bugs on it.

That is why I have changed the script to support the old ParamSpider tool and it only supports a single domain as of now.

I will try to add the new feature of supporting multiple domains as input via a text file in the coming days.

Stay tuned for a few days.

**Comment by math-ematics** [comment]
how did this work out? been a few days now

**Comment by 0xKayala** [comment]
Can someone try to execute the scripts given in the below issue and let me know which version of the script is working from your end?

[Issue Link](https://github.com/0xKayala/NucleiFuzzer/issues/20)

**Comment by Tripse** [comment]
I'm very sorry, I'm very busy this month, proposing new features to you but don't have time to provide code. Thank you very much for your reply. This tool is great

**Comment by Tripse** [comment]
> The newly updated ParamSpider supports -f or file.txt, but it is not giving an accurate result of output where nuclei cannot detect bugs on it.
> 
> That is why I have changed the script to support the old ParamSpider tool and it only supports a single domain as of now.
> 
> I will try to add the new feature of supporting multiple domains as input via a text file in the coming days.
> 
> Stay tuned for a few days.

I'm very sorry, I'm very busy this month, proposing new features to you but don't have time to provide code. Thank you very much for your reply. This tool is great

**Comment by 0xKayala** [comment]
Anyway, I have added the multiple URLs support now. I hope it is working fine now
